### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by dominicpalmer** [justcla/HotTabs#1]
Hi Justin. Is there a plan to bring HotTabs to VS2022? There's no VS Markeplace alternative to what HotTabs offers as far as I can see, so I'd love to see it stay up to date with newer VS releases.

**Comment by justcla** [comment]
Sure thing. I'll see if I can update it to VS2022 for you.
I've just been waiting for someone to ask. Didn't think anybody cared. 😉

**Comment by justcla** [comment]
By the way, the code for this came from Custom Document Well  (CDW), part of the Productivity Power Tools (PPT).
https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.CustomDocumentWell
I notice this one (owned by the Visual Studio team) hasn't been updated since 2017.

I notice there is a new release of PPT for 2022.
https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ProductivityPowerPack2022
But it seems they have not included Custom Document Well in this release.

I know there was talk in the team about whether to build CDW into VS - because a survey showed it was one of the most popular features of PPT. So maybe that's why it's not a separate extension any more.
But maybe they forgot to include the shortcut commands for binding.

**Comment by dominicpalmer** [comment]
Awesome, thank you. I think the extension is great. Being able to select tabs by index is a huge timesaver for me. In fact, you'll notice a 'Hot Tabs' shaped TODO in my refreshed VS2022 VSVim config:

https://github.com/dominicpalmer/dotfiles/blob/e673748995f832bc743876cb8a10f76dcb9770f9/windows/vs/.vimrc?plain=1#L167-L169

I wasn't aware that the code came from PPT either - good to know. Will keep an eye out to see if CDW gets built into VS in the future. It would seem likely, given it's been taken out of PPT already for the 2022 release.

**Comment by justcla** [comment]
Done. I have uploaded a [VS2022 version](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.HotTabs) to the Marketplace.

**Comment by dominicpalmer** [comment]
Many thanks
